### ISSUE TITLE
Composer 2 support on PHP 7.4 images

### ISSUE THREAD

**Issue by dan2k3k4** [uselagoon/lagoon-images#265]
Currently [composer](http://getcomposer.org/) is added into the [`amazeeio/php` Dockerfile image](https://github.com/amazeeio/lagoon/blob/0e51f7b74d0b24473ca21d22fb7c0a1aa3029d8d/images/php/cli/Dockerfile#L10-L38) at version `1.10.9`.

We can update composer to the latest release by adding the following before we do the `RUN composer install` line in our own CLI Dockerfile for each project:

`RUN composer self-update --2`

This will update to the latest preview release, which is currently `2.0.0-RC2`

There is no specific date yet for when Composer v2 will be out, however the [milestone is at 92%](https://github.com/composer/composer/milestone/23).

There is documentation on the upgrade step from [v1 to v2](https://getcomposer.org/upgrade/UPGRADE-2.0.md).

Eventually the Docker Hub image for `composer` will be updated to use v2 so our health checks will fail as we use [FROM composer:latest](https://github.com/amazeeio/lagoon/blob/0e51f7b74d0b24473ca21d22fb7c0a1aa3029d8d/images/php/fpm/Dockerfile#L7).

Do we need to implement a plan to support v2 across Lagoon and then allow people to do a `RUN composer self-update --1` to rollback to v1 for legacy?

Do we want to document how people can already upgrade to v2 for their own projects by adding `RUN composer self-update --2`?

**Comment by mxr576** [comment]
So this issue is still open and I have opened #265 yesterday which is also related to that. What is the plan here?

I see PHP 8.0 images come with Composer 2 by default, but 7.4 (and earlier versions) are still on Composer 1. Is it the plain to wait one more year until 7.4 is also EOL-ed...? I hope not :) 
There are packages already which are not available for Composer 1 on Packagist: https://blog.packagist.com/deprecating-composer-1-support/

Do you have any metrics about how many projects are running builds with still Composer 1 on Lagoon? Having that data could be step 0 for starting to phase out Composer 1 and instead of suggesting Lagoon image users customize docker files (and diverge from upstream Docker images) for using Composer 2, they should customize it for sticking with Composer 1 still. (This is their technical debt.) Maybe a warning can be displayed in builds, a notification email could be already sent to those project maintainers who are still building with Composer 1.

**Comment by tobybellwood** [comment]
With our recent experiences on composer2, I'm unwilling to foist it on sites that are still running composer1 on php74 (especially with ~4 months to EOL).

The advice we do give is that for people who want composer2 on php7.4 (and are hitting the hirak/prestissimo bug with allow-plugins), is to use this code snippet in your Dockerfile to remove the package and upgrade to 2 in one step:

```
RUN composer global remove hirak/prestissimo \
	&& composer self-update --2 \
	&& composer install {plus any install options you have}
```

This will:
a) use composer 1 to remove the globally installed hirak/prestissimo from the image
b) upgrade Composer to the latest stable 2.x version (you could specify a particular version here too)
c) proceed with the composer install using composer2

You will still need to ensure that any plugins are correctly specified in the allow-plugins section of your composer.json

**Comment by TomvEtten** [comment]
Well, the ideal situation is 'promoting' a migration to 2, but the image supporting 1 and 2. 

Removing the following line :   [&& php -d memory_limit=-1 /usr/local/bin/composer global require hirak/prestissimo \](https://github.com/uselagoon/lagoon/blob/0e51f7b74d0b24473ca21d22fb7c0a1aa3029d8d/images/php/cli/Dockerfile#L40) will do both. Users stil can use composer 1 (with degraded performance, they can still require it themselves), and users can choose to update and use composer 2. Supporting both cases should be better than needing to adjust for 1.

**Comment by tobybellwood** [comment]
Waiting on https://github.com/composer/docker/pull/253 to be able to release updated images with these fixes
