### ISSUE TITLE
Add Solr 8.x, update to 7.7.3, deprecate 5.x and 6.x

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#31]
## Solr 8.x

I was wondering if we could also support Solr 8.x. The [current stable version](https://lucene.apache.org/solr/downloads.html) is `8.6.3`.

https://www.drupal.org/project/search_api_solr supports 8.x with the 4.x version of the Drupal module too.

Looks like there are openjdk images on Alpine now https://github.com/docker-library/openjdk/blob/master/16/jdk/alpine3.12/Dockerfile

## Solr 7.7.x

We are running `7.7.1` to which has security issues associated with it, we should default to `7.7.3`. (to which is still in support).

## Solr < 7.7

All older versions (<7.7) are [End Of Life (EOL)](https://lucene.apache.org/solr/downloads.html#about-versions-and-support), and we should indicate this just like we do for PHP and drop support for them.

## Task List

- [x] Deprecate Solr 5.5 & 6.6 #281
- [x] Add Solr 7.7.3 image #128 - `uselagoon/solr-7` and `uselagoon/solr-7-drupal`
- [x] Add Solr 8 image

**Comment by tobybellwood** [comment]
So, this is pretty involved (some backstory at https://github.com/amazeeio/lagoon/issues/1324#issuecomment-601902121).

- The last upstream alpine-based image (docker/Solr) published was 7.7.1
- The upstream of the upstream (OpenJDK), stopped supporting alpine in v8
- The upstream (docker/Solr) has outlined a preference for using JRE (instead of JDK) to reduce size.

We're pretty much going to have to either:
- roll our own alpine-based Solr images :scream: 
- change the base to Debian-slim for Solr (which means also remaking the commons image for Debian)

Either way, this is a largish piece of work, and not without possible complications...

**Comment by tobybellwood** [comment]
work underway in https://github.com/uselagoon/lagoon-images/pull/97

One thing to note is that Lagoon prebackuppods are hardcoded to use busybox tar - which won't work on debian-slim based images.

**Comment by mxr576** [comment]
Solr 7.7 does not get all the security updates that Solr 8 does. Somehow resolving this issue has to become a priority because we get more and more security reports about using "outdated" Solr version.

**Comment by tobybellwood** [comment]
Solr 8 plan:

- Introduce new script `lagoon-recreate-solr` or similar to wrap around https://github.com/docker-solr/docker-solr/blob/master/8.10/scripts/solr-precreate
- This can then be called as the CMD in the [solr](https://github.com/uselagoon/lagoon-images/blob/main/images/solr/7.Dockerfile#L63) and [solr-drupal](https://github.com/uselagoon/lagoon-images/blob/main/images/solr-drupal/7.Dockerfile#L9) dockerfiles

**Comment by rocketeerbkw** [comment]
Solr 8 images were added in 22.2.0, all tasks complete.
