### ISSUE TITLE
php-fpm terminates immediately instead of performing a graceful shutdown

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-images#444]
I noticed that sometimes when deployments are scaled down a `502` response is returned for in-flight web requests. I think I figured out why:

In Kubernetes when a deployment is being scaled down pods will be terminated. This occurs by sending a signal to PID 1 in the pod's containers. That signal is SIGTERM by default, but container runtimes will respect the `StopSignal` in the container metadata.

`php-fpm` handles a couple of different [termination signals](https://manpages.debian.org/testing/php7.0-fpm/php-fpm7.0.8.en.html#SIGNAL):

```
SIGINT,SIGTERM immediate termination
SIGQUIT graceful stop
```

The Lagoon `php-fpm` images inherit the "graceful stop" signal from the `php` base image:

```
$ docker inspect uselagoon/php-8.1-fpm | grep StopSignal
            "StopSignal": "SIGQUIT"
```

However there is [another config option](https://www.php.net/manual/en/install.fpm.configuration.php) which affects the behaviour of `php-fpm`:

```
 process_control_timeout
    Time limit for child processes to wait for a reaction on signals from master. Available units: s(econds), m(inutes), h(ours), or d(ays) Default Unit: seconds. Default value: 0.
```

This is _not_ configured in Lagoon `php-fpm` images which means that it defaults to `0`. Even though Kubernetes uses the "graceful stop" signal `SIGQUIT`, `php-fpm` will not wait for child process to exit and instead will kill them immediately.

If `process_control_timeout` is set to something more reasonable like `30s` it would [help to avoid request errors on pod termination](https://serverfault.com/a/917142). `30s` also matches the Kubernetes [default grace period](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination).

I would send a PR, but the `process_control_timeout` is a global `php-fpm` config option, and not a pool option. I don't think the Lagoon `php-fpm` image currently has a global config file so it is not as simple as a single-line PR. Instead we would need to figure out how to integrate such a global config into the image.

**Comment by Schnitzel** [comment]
oh wow, epic found, I was always testing with nginx if it's gracefully stopping (as I assumed that the php-fpm processes are controlled by nginx), but seems that this was wrong.

So I checked our php images and found that indeed the global php-fpm config file which is at `/usr/local/etc/php-fpm.conf` is not shipped in our images, it's not even added by the upstream php Dockerfile (https://github.com/docker-library/php/blob/master/8.1/alpine3.15/fpm/Dockerfile) it instead comes from the PHP package itself.

Interestingly we `ep` it: https://github.com/uselagoon/lagoon-images/blob/fd619797e02ce4eacef5a71a52559f0935c2b2bc/images/php-fpm/entrypoints/70-php-config.sh#L4 but there is nothing to ep in there.

So I see two ways how to fix this:
1. ship our own `php-fpm.conf` file and add this config as a configurable setting via `ep` (and make it 30 secs by default). With this we have full control and could also change any other PHP FPM global settings if we ever have too. The problem is that if PHP adds anything to the file we are not aware we probably going to run into an issue (even though that likelyhood is super small)
2. we modify the `php-fpm.conf` on the fly during building, we are already doing something similar here: https://github.com/uselagoon/lagoon-images/blob/fd619797e02ce4eacef5a71a52559f0935c2b2bc/images/php-fpm/8.1.Dockerfile#L77 so there would be precedence for this.

Personally I'm for inclined for Variant 1.

**Comment by smlx** [comment]
I found that we can just stick a `[global]` section at the top of our existing `www.conf` which seems to work. See #445 for details.
