### ISSUE TITLE
Opensearch Images to replace Elasticsearch Images

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-images#501]
As we will not release any Elasticsearch Images anymore we should focus on getting Opensearch Images out. 

There is a PR with experimental OpenSearch Images: https://github.com/uselagoon/lagoon-images/pull/373 but not sure how far we are there.

**Comment by tobybellwood** [comment]
I'm needing to pick this back up again now that the images are at v2. We had some issues with the upstream Lagoon template permissions (https://github.com/uselagoon/lagoon/pull/3126). Will re-evaluate now.

Because of renaming etc, it won't be a drop-in replacement for Elasticsearch, but shouldn't be too hard to migrate to.

**Comment by tobybellwood** [comment]
opensearch-2 images are available now
