### ISSUE TITLE
Add `jq` and `yq` to the base PHP CLI images

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#690]
Useful for lots of things. Should not add too much to the image size either.

This will mean child images will not need to do this themselves, e.g. https://github.com/govCMS/lagoon/blob/2.x-develop/.docker/Dockerfile.govcms#L16-L22

**Comment by tobybellwood** [comment]
I've thought about this in the past (adding to all base images!), and my reasoning for not doing it (to date) was thus:

* There's two slightly different implementations of jq - https://github.com/itchyny/gojq (current) and https://github.com/stedolan/jq (outdated) - that handle certain situations differently - and may cause issues to downstream users
* yq had a massive b/c change from 3 to 4 - if we added the alpine-provided version in the base image, it would have rendered people's apps rebuildable in an alpine update (3.13-3.14) to the base images. It is more stable now, so less of a risk.

I'm happy to be persuaded otherwise, but these are tools that are quite niche/specialist in their use, and their install/version control is maybe best left to the people using them? Obviously if there is Lagoon merit in including them for use in entrypoints, then that is something we can consider?

As for the linked install script - a perfect example - yq is already in the alpine pkg library at version 4.3.0 (https://pkgs.alpinelinux.org/package/v3.17/community/x86/yq), and the linked install is for a very incompatible v2.4.0

**Comment by smlx** [comment]
`gojq` has `--yaml-input` and `--yaml-output`, so if this feature happens `yq` might not even be required.

**Comment by tobybellwood** [comment]
Now that stdolan has transferred JQ to https://github.com/jqlang and it's been resusciated, there's again division in the jq world that makes it hard for us to standardise for people.
