### ISSUE TITLE
PHP 23.8.0 broke Drupal sites without `cookie_samesite: Lax` set in `services.yml`

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#823]
After upgrading sites without `cookie_samesite: Lax` set in `services.yml`, it is not possible to login - an error `To log in to this site, your browser must accept cookies from the domain` is shown.

This PR https://github.com/uselagoon/lagoon-images/pull/755 introduced the overrides for `cookie_samesite` with a default value of `None`.

`None` has a special value when written in INI files. As per [this](https://bugs.php.net/bug.php?id=78651) bug report, it should be quoted `"None"`.

The tests are not checking for quoted `"None"` https://github.com/uselagoon/lagoon-images/pull/755/files#diff-ef4add63b95387c9d137ce74198e6b3f5ae2d53d4218ce505831c8734a61ed13R348

With that said, it is not clear why, while having the value set to un-quoted `None` in ini, the `cookie_samesite` behaves like `Strict`.

The workaround is to simply add `cookie_samesite: Lax` to the site's `services.yml`.

**Comment by rocketeerbkw** [comment]
Our php images do quote the ini value as `"None"`:
```bash
➜  ~ docker run --rm -it uselagoon/php-8.1-cli:23.8.0 \
grep samesite /usr/local/etc/php/conf.d/00-lagoon-php.ini 

configured lagoon-php.ini
session.cookie_samesite = "None"
```

I tested our Drupal 10 example and OOTB I was able to login without issues. The [core services.yml](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/core.services.yml#L15) and the [default.services.yml](https://git.drupalcode.org/project/drupal/-/blob/11.x/sites/default/default.services.yml#L45) both use `Lax` already, which overrides the php.ini value. Which option was set for your sites that broke?

Perhaps `"None"` is not a good default, since it requires the secure attribute to be true also, and is not compatible with older browsers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value

**Comment by AlexSkrypnyk** [comment]
@rocketeerbkw 
thank you for working on this!

I can confirm that this affects non-Drupal sites (Matomo) - the `cookie_samesite` value gets mixed up and it is not possible to login locally.

It would be great to have this merged into a latest release.

**Comment by tobybellwood** [comment]
@AlexSkrypnyk if you want to reconfirm locally - the images for this PR are at `testlagoon/php-8.1-cli:pr-823` etc

**Comment by AlexSkrypnyk** [comment]
Just a temp workaround - add the following to `docker-compose.yml`:
```yaml
x-environment
  PHP_SESSION_COOKIE_SAMESITE: ""
```
