### ISSUE TITLE
Use pinned package versions in images

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#923]
Only some of the alpine packages use specific versions or version constraints.

Best practices and linters such as Hadolint suggest using pinned packages versions.

https://github.com/hadolint/hadolint/wiki/DL3018
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Can all of the Dockerfiles be updated to use versions?
Renovate will be able to update the version string automatically.

**Comment by tobybellwood** [comment]
aha - been there done that, got the t-shirt!

Because Alpine's package manager only supports a single release of a package per alpine version, there is no concept of "upgraded versions" - i.e the nodejs-current package at alpine3.18 is version 20.8.1 (https://pkgs.alpinelinux.org/package/v3.18/community/amd64/nodejs-current).  We pin this package to v20, mostly to remind us that it is that version, and if the version of alpine updates, and that package is no longer v20, we have a decision to make.

So whilst RenovateBot would happily create PRs for the new releases, it would be a moot point, as the second a new version is available, the previous version is instantly unavailble (ie.20.5.0 above https://git.alpinelinux.org/aports/commit/?id=0c746baf68e2d4f878301dbff4c98e135187700e)

Obviiously this is only alpine, but, you can see why it doesn't matter!

**Comment by tobybellwood** [comment]
What we will be working on is making any package version changes between releases easier to track, and enhancing some of the supply chain vulnerability and security measures.

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
Thank you for a detailed explanation.

Is there a link that talks about "Alpine's package manager only supports a single release of a package per alpine version"? Because it seems a bit strange that there is a versioning system in place but there is only a single version per alpine release.

**Comment by tobybellwood** [comment]
ha, the docs are a little lacking on this, but there is an issue explaining why https://gitlab.alpinelinux.org/alpine/abuild/-/issues/9996#note_87135

There is some hadolint discussion on this https://github.com/hadolint/hadolint/issues/204

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
Thank you for these references!

Looking at https://github.com/hadolint/hadolint/issues/204#issuecomment-394103224 and the number of 👍's, it is possible to use `~=` to set only the first part of the version. But then it kinda defeats the whole point of having a specific version.

I'm closing this one. Thank you!
